### ISSUE TITLE
Proble with Terraform state blob access key

### ISSUE THREAD

**Issue by angusmack-altius** [JimPaine/aks-quickstart#1]
Hi Jim,

Really please you posted this as I've done something very similar by hand and was just about to Terraform it when you published this.

I've followed all your steps but I think you missed added the blob storage access key as a pipeline variable.

![image](https://user-images.githubusercontent.com/43994273/55671160-d7258b00-5884-11e9-9d07-bb177d28ce7b.png)

I added this and now it works fine.

Cheers,
Angus

**Comment by JimPaine** [comment]
Thanks for this @angusmack-altius I have added the missing variable from the variable group.
