### ISSUE TITLE
values.yaml

### ISSUE THREAD

**Issue by angusmack-altius** [JimPaine/aks-quickstart#2]
Hi Jim - this file probably shouldn't be checked in should it?

**Comment by JimPaine** [comment]
Cheers, Angus. This shouldn't have been. This was is hang over from where I was exploring pod identity.

Fixed through [this](https://github.com/JimPaine/aks-quickstart/commit/e658ba996f8e75d3163b9c3bcb08f1601c961685#diff-477e476cda62fb98ce088ee3c96d2166) commit
