### ISSUE TITLE
ServicePrincipal

### ISSUE THREAD

**Issue by smandava** [JimPaine/aks-quickstart#3]
Hey Jim, Can you share some information on how to create and setup permissions on the ServicePricipal?

`terraform apply` works fine, if I comment out these blocks in the `providers.tf` and [Authenticate using the Azure CLI](https://www.terraform.io/docs/providers/azurerm/auth/azure_cli.html) 

```
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
```

But I'm getting authorization error creating `azuread_application` resource [if I use Service Principal with a Client Secret](https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_secret.html)

```
 azuread_application.aks: graphrbac.ApplicationsClient#Create: Failure responding to request:
 StatusCode=403 -- Original Error: autorest/azure: Service returned an error. 
Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":
{"code":"Authorization_RequestDenied","date":"2019-08-04T14:41:58","message":
{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"xxx"}}]
```

**Comment by JimPaine** [comment]
HI @smandava sorry for the delay in getting back to you, I must have screwed up my notifications. It sounds like you need to give the service principal permissions on your subscription you want to provision resources, see the link below.

[Grant service principal permissions on Azure Subscription](https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_secret.html#3-granting-the-application-access-to-manage-resources-in-your-azure-subscription
)

Let me know if you hit any more issues

**Comment by smandava** [comment]
No problem and thanks for the information Jim. 

After assigning proper role as you suggested above and following the steps mentioned in [ your docs page](https://github.com/JimPaine/aks-quickstart/blob/master/docs/TerraformSP.md)  my terraform modules are working now.

Thanks again for the help!
